name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
